name: "Test public from main"
on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  public_test:
    strategy:
      fail-fast: false
      matrix:
        version: ["1.7.0", "1.8.2", "1.9.0", "1.10.0", "1.11.0", "latest"]
    runs-on: ubuntu-latest
    env:
      BATS_LIB_PATH: "/usr/lib"
      TERM: xterm
    name: Install Bats common libs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bats and Bats-libs
        uses: stealthii/bats-action@main
        with:
          bats-version: ${{ matrix.version }}
          support-clean: "false"
          assert-clean: "false"
          detik-clean: "false"
          file-clean: "false"
      - name: Execute test to check Bats-support
        run: |
          cd /tmp/bats-support/
          bats test
      - name: Execute test to check  Bats-assert
        run: |
          cd /tmp/bats-assert/
          bats test
      - name: Execute test to check Bats-detik
        run: |
          cd /tmp/bats-detik/
          bats tests
      - name: Execute test to check Bats-file
        continue-on-error: true
        run: |
          cd /tmp/bats-file/
          bats test
      - name: Execute example tests
        run:
          bats -T -p tests
  public_test_trigger_cache:
    # Run the test again to eventually trigger the cache in the future
    needs: [public_test]
    strategy:
      fail-fast: false
      matrix:
        version: ["1.7.0", "1.8.2", "1.9.0", "1.10.0", "1.11.0", "latest"]
    runs-on: ubuntu-latest
    env:
      BATS_LIB_PATH: "/usr/lib"
    name: Install Bats common libs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bats and Bats-libs
        uses: bats-core/bats-action@main
        with:
          bats-version: ${{ matrix.version }}
          support-clean: "false"
          assert-clean: "false"
          detik-clean: "false"
          file-clean: "false"
      - name: Execute test to check Bats-support
        run: |
          cd /tmp/bats-support/
          bats test
      - name: Execute test to check  Bats-assert
        run: |
          cd /tmp/bats-assert/
          bats test
      - name: Execute test to check Bats-detik
        run: |
          cd /tmp/bats-detik/
          bats tests
      - name: Execute test to check Bats-file
        continue-on-error: true
        run: |
          cd /tmp/bats-file/
          bats test
